local_backend: false
backend:
  branch: main
  name: git-gateway
media_folder: /src/public
collections:
  - name: blog
    label: Blog
    folder: blog
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - name: body
        widget: markdown
