local_backend: false
backend:
  branch: main
  name: git-gateway
media_folder: /src/public
editor:
  preview: false
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: 'src/blog'
    create: true
    preview_path: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - name: body
        widget: markdown
  - name: news
    label: News
    folder: 'src/news'
    create: true
    preview_path: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - name: body
        widget: markdown
