local_backend: false
backend:
  branch: main
  name: git-gateway
media_folder: /src/public
editor:
  preview: false
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: 'src/blog'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}_{{slug}}"
    preview_path: 'blog/{{slug}}'
    summary: "{{title}} (最後更新: {{commit_date}})"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - name: body
        widget: markdown
  - name: news
    label: News
    folder: 'src/news'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}_{{slug}}"
    preview_path: 'news/{{slug}}'
    summary: "{{title}} (最後更新: {{commit_date}})"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - name: body
        widget: markdown
